package com.pujun.webcrawler.dao;

import java.util.List;

import com.pujun.webcrawler.entity.Dazhongdianping;


public interface DazhongdianpingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dazhongdianping
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	int insert(Dazhongdianping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dazhongdianping
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	int insertSelective(Dazhongdianping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dazhongdianping
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	Dazhongdianping selectByPrimaryKey(String shopid);
	
	List<Dazhongdianping> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dazhongdianping
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	int updateByPrimaryKeySelective(Dazhongdianping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dazhongdianping
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	int updateByPrimaryKey(Dazhongdianping record);
}