package com.pujun.webcrawler.dao;

import com.pujun.webcrawler.entity.Proxy;
import com.pujun.webcrawler.entity.ProxyKey;

public interface ProxyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Sun Apr 16 17:07:34 CST 2017
     */
    int insert(Proxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Sun Apr 16 17:07:34 CST 2017
     */
    int insertSelective(Proxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Sun Apr 16 17:07:34 CST 2017
     */
    Proxy selectByPrimaryKey(ProxyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Sun Apr 16 17:07:34 CST 2017
     */
    int updateByPrimaryKeySelective(Proxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy
     *
     * @mbg.generated Sun Apr 16 17:07:34 CST 2017
     */
    int updateByPrimaryKey(Proxy record);
}