package com.pujun.webcrawler.entity;

import java.util.Date;

public class Hauses extends HausesKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.price
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.areaName
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String areaname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.community
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String community;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.huxing
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String huxing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.louceng
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String louceng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.jianmian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private Float jianmian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.taomian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private Float taomian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.louxing
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String louxing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.chaoxiang
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String chaoxiang;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.jiegou
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String jiegou;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.zhuangxiu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String zhuangxiu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.tihubili
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String tihubili;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.gongnuan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String gongnuan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.hasDianti
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String hasdianti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.chanquan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String chanquan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.jiaoyiquanshu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String jiaoyiquanshu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.guapaishijian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String guapaishijian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.shangcijiaoyi
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String shangcijiaoyi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.yongtu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String yongtu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.chiyounianxian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String chiyounianxian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.suoyouquan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String suoyouquan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.diya
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String diya;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.note
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.createtime
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private Date createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.price
	 * @return  the value of hauses.price
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.price
	 * @param price  the value for hauses.price
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.areaName
	 * @return  the value of hauses.areaName
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getAreaname() {
		return areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.areaName
	 * @param areaname  the value for hauses.areaName
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.community
	 * @return  the value of hauses.community
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getCommunity() {
		return community;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.community
	 * @param community  the value for hauses.community
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setCommunity(String community) {
		this.community = community;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.huxing
	 * @return  the value of hauses.huxing
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getHuxing() {
		return huxing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.huxing
	 * @param huxing  the value for hauses.huxing
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setHuxing(String huxing) {
		this.huxing = huxing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.louceng
	 * @return  the value of hauses.louceng
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getLouceng() {
		return louceng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.louceng
	 * @param louceng  the value for hauses.louceng
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setLouceng(String louceng) {
		this.louceng = louceng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.jianmian
	 * @return  the value of hauses.jianmian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public Float getJianmian() {
		return jianmian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.jianmian
	 * @param jianmian  the value for hauses.jianmian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setJianmian(Float jianmian) {
		this.jianmian = jianmian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.taomian
	 * @return  the value of hauses.taomian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public Float getTaomian() {
		return taomian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.taomian
	 * @param taomian  the value for hauses.taomian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setTaomian(Float taomian) {
		this.taomian = taomian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.louxing
	 * @return  the value of hauses.louxing
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getLouxing() {
		return louxing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.louxing
	 * @param louxing  the value for hauses.louxing
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setLouxing(String louxing) {
		this.louxing = louxing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.chaoxiang
	 * @return  the value of hauses.chaoxiang
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getChaoxiang() {
		return chaoxiang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.chaoxiang
	 * @param chaoxiang  the value for hauses.chaoxiang
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setChaoxiang(String chaoxiang) {
		this.chaoxiang = chaoxiang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.jiegou
	 * @return  the value of hauses.jiegou
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getJiegou() {
		return jiegou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.jiegou
	 * @param jiegou  the value for hauses.jiegou
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setJiegou(String jiegou) {
		this.jiegou = jiegou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.zhuangxiu
	 * @return  the value of hauses.zhuangxiu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getZhuangxiu() {
		return zhuangxiu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.zhuangxiu
	 * @param zhuangxiu  the value for hauses.zhuangxiu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setZhuangxiu(String zhuangxiu) {
		this.zhuangxiu = zhuangxiu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.tihubili
	 * @return  the value of hauses.tihubili
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getTihubili() {
		return tihubili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.tihubili
	 * @param tihubili  the value for hauses.tihubili
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setTihubili(String tihubili) {
		this.tihubili = tihubili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.gongnuan
	 * @return  the value of hauses.gongnuan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getGongnuan() {
		return gongnuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.gongnuan
	 * @param gongnuan  the value for hauses.gongnuan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setGongnuan(String gongnuan) {
		this.gongnuan = gongnuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.hasDianti
	 * @return  the value of hauses.hasDianti
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getHasdianti() {
		return hasdianti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.hasDianti
	 * @param hasdianti  the value for hauses.hasDianti
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setHasdianti(String hasdianti) {
		this.hasdianti = hasdianti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.chanquan
	 * @return  the value of hauses.chanquan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getChanquan() {
		return chanquan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.chanquan
	 * @param chanquan  the value for hauses.chanquan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setChanquan(String chanquan) {
		this.chanquan = chanquan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.jiaoyiquanshu
	 * @return  the value of hauses.jiaoyiquanshu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getJiaoyiquanshu() {
		return jiaoyiquanshu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.jiaoyiquanshu
	 * @param jiaoyiquanshu  the value for hauses.jiaoyiquanshu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setJiaoyiquanshu(String jiaoyiquanshu) {
		this.jiaoyiquanshu = jiaoyiquanshu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.guapaishijian
	 * @return  the value of hauses.guapaishijian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getGuapaishijian() {
		return guapaishijian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.guapaishijian
	 * @param guapaishijian  the value for hauses.guapaishijian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setGuapaishijian(String guapaishijian) {
		this.guapaishijian = guapaishijian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.shangcijiaoyi
	 * @return  the value of hauses.shangcijiaoyi
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getShangcijiaoyi() {
		return shangcijiaoyi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.shangcijiaoyi
	 * @param shangcijiaoyi  the value for hauses.shangcijiaoyi
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setShangcijiaoyi(String shangcijiaoyi) {
		this.shangcijiaoyi = shangcijiaoyi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.yongtu
	 * @return  the value of hauses.yongtu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getYongtu() {
		return yongtu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.yongtu
	 * @param yongtu  the value for hauses.yongtu
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setYongtu(String yongtu) {
		this.yongtu = yongtu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.chiyounianxian
	 * @return  the value of hauses.chiyounianxian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getChiyounianxian() {
		return chiyounianxian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.chiyounianxian
	 * @param chiyounianxian  the value for hauses.chiyounianxian
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setChiyounianxian(String chiyounianxian) {
		this.chiyounianxian = chiyounianxian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.suoyouquan
	 * @return  the value of hauses.suoyouquan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getSuoyouquan() {
		return suoyouquan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.suoyouquan
	 * @param suoyouquan  the value for hauses.suoyouquan
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setSuoyouquan(String suoyouquan) {
		this.suoyouquan = suoyouquan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.diya
	 * @return  the value of hauses.diya
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getDiya() {
		return diya;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.diya
	 * @param diya  the value for hauses.diya
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setDiya(String diya) {
		this.diya = diya;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.note
	 * @return  the value of hauses.note
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.note
	 * @param note  the value for hauses.note
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.createtime
	 * @return  the value of hauses.createtime
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.createtime
	 * @param createtime  the value for hauses.createtime
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
}