package com.pujun.webcrawler.entity;

import java.util.Date;

public class HausesKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.id
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hauses.crawldate
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	private Date crawldate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.id
	 * @return  the value of hauses.id
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.id
	 * @param id  the value for hauses.id
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hauses.crawldate
	 * @return  the value of hauses.crawldate
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public Date getCrawldate() {
		return crawldate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hauses.crawldate
	 * @param crawldate  the value for hauses.crawldate
	 * @mbg.generated  Sun Apr 16 17:07:34 CST 2017
	 */
	public void setCrawldate(Date crawldate) {
		this.crawldate = crawldate;
	}
}