package com.kingfong.webcrawler.entity;

import java.util.Date;

public class Dazhongdianping {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.shopId
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String shopid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.shopName
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String shopname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.addr_province
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String addrProvince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.addr_city
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String addrCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.addr_district
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String addrDistrict;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.addr
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.phoneNo
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String phoneno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.mobilePhone
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String mobilephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.shopType
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String shoptype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.comPerPerson
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String comperperson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.level
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.workTime
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private String worktime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dazhongdianping.fetchtime
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	private Date fetchtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.shopId
	 * @return  the value of dazhongdianping.shopId
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getShopid() {
		return shopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.shopId
	 * @param shopid  the value for dazhongdianping.shopId
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setShopid(String shopid) {
		this.shopid = shopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.shopName
	 * @return  the value of dazhongdianping.shopName
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getShopname() {
		return shopname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.shopName
	 * @param shopname  the value for dazhongdianping.shopName
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.addr_province
	 * @return  the value of dazhongdianping.addr_province
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getAddrProvince() {
		return addrProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.addr_province
	 * @param addrProvince  the value for dazhongdianping.addr_province
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setAddrProvince(String addrProvince) {
		this.addrProvince = addrProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.addr_city
	 * @return  the value of dazhongdianping.addr_city
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getAddrCity() {
		return addrCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.addr_city
	 * @param addrCity  the value for dazhongdianping.addr_city
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setAddrCity(String addrCity) {
		this.addrCity = addrCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.addr_district
	 * @return  the value of dazhongdianping.addr_district
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getAddrDistrict() {
		return addrDistrict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.addr_district
	 * @param addrDistrict  the value for dazhongdianping.addr_district
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setAddrDistrict(String addrDistrict) {
		this.addrDistrict = addrDistrict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.addr
	 * @return  the value of dazhongdianping.addr
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.addr
	 * @param addr  the value for dazhongdianping.addr
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.phoneNo
	 * @return  the value of dazhongdianping.phoneNo
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getPhoneno() {
		return phoneno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.phoneNo
	 * @param phoneno  the value for dazhongdianping.phoneNo
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.mobilePhone
	 * @return  the value of dazhongdianping.mobilePhone
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getMobilephone() {
		return mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.mobilePhone
	 * @param mobilephone  the value for dazhongdianping.mobilePhone
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.shopType
	 * @return  the value of dazhongdianping.shopType
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getShoptype() {
		return shoptype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.shopType
	 * @param shoptype  the value for dazhongdianping.shopType
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setShoptype(String shoptype) {
		this.shoptype = shoptype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.comPerPerson
	 * @return  the value of dazhongdianping.comPerPerson
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getComperperson() {
		return comperperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.comPerPerson
	 * @param comperperson  the value for dazhongdianping.comPerPerson
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setComperperson(String comperperson) {
		this.comperperson = comperperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.level
	 * @return  the value of dazhongdianping.level
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.level
	 * @param level  the value for dazhongdianping.level
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.workTime
	 * @return  the value of dazhongdianping.workTime
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public String getWorktime() {
		return worktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.workTime
	 * @param worktime  the value for dazhongdianping.workTime
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setWorktime(String worktime) {
		this.worktime = worktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dazhongdianping.fetchtime
	 * @return  the value of dazhongdianping.fetchtime
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public Date getFetchtime() {
		return fetchtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dazhongdianping.fetchtime
	 * @param fetchtime  the value for dazhongdianping.fetchtime
	 * @mbggenerated  Mon Oct 19 15:23:43 CST 2015
	 */
	public void setFetchtime(Date fetchtime) {
		this.fetchtime = fetchtime;
	}

	@Override
	public String toString() {
		return "Dazhongdianping [shopid=" + shopid + ", shopname=" + shopname + ", addrProvince=" + addrProvince
				+ ", addrCity=" + addrCity + ", addrDistrict=" + addrDistrict + ", addr=" + addr + ", phoneno="
				+ phoneno + ", mobilephone=" + mobilephone + ", shoptype=" + shoptype + ", comperperson=" + comperperson
				+ ", level=" + level + ", worktime=" + worktime + ", fetchtime=" + fetchtime + "]";
	}
    
}
